# livox_ros_driver2 configuration file
# Configuration for dual MID-360 setup
livox_ros_driver2_node:
  ros__parameters:
    xfer_format: 0      # 0-Pointcloud2(PointXYZRTL), 1-customized pointcloud format
    multi_topic: 0      # 0-All LiDARs share the same topic, 1-One LiDAR one topic
                        # MUST be 1 for dual sensor setup with separate topics
    data_src: 0         # 0-lidar, others-Invalid data src
    publish_freq: 10    # freqency of publish, 5.0, 10.0, 20.0, 50.0, etc.
    output_data_type: 0
    frame_id: "livox_frame"
    lvx_file_path: "/home/livox/livox_test.lvx"
    user_config_path: "<package_share>/config/multiple_netconfigs.json"
    cmdline_input_bd_code: "livox0000000001"